# Generated by Django 4.2.16 on 2024-09-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_date_joined_user_first_name_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('lender', 'Lender'), ('borrower', 'Borrower')], max_length=255, null=True),
        ),
    ]
