PAYMENT_STATUS_PENDING = 'pending'
PAYMENT_STATUS_PAID = 'paid'
PAYMENT_STATUS_OVERDUE = 'overdue'

PAYMENT_STATUS_CHOICES = [
    (PAYMENT_STATUS_PENDING, 'Pending'),
    (PAYMENT_STATUS_PAID, 'Paid'),
    (PAYMENT_STATUS_OVERDUE, 'Overdue'),
]
