# Generated by Django 4.2.16 on 2024-09-07 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_months', models.IntegerField(default=6)),
                ('annual_interest_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('lenme_fee', models.DecimalField(decimal_places=2, default=3.75, max_digits=5)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Funded', 'Funded'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_loans', to=settings.AUTH_USER_MODEL)),
                ('lender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funded_loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
