# Generated by Django 4.2.16 on 2024-09-07 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
