# Generated by Django 4.2.16 on 2024-09-07 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_superuser'),
        ('loans', '0004_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_loans', to='users.borrower'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funded_loans', to='users.lender'),
        ),
    ]
