# Generated by Django 4.2.16 on 2024-09-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_alter_loan_borrower_alter_loan_lender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='lenme_fee',
            new_name='admin_fee',
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('funded', 'Funded'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
