# Generated by Django 4.2.16 on 2024-09-09 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0006_delete_testmodel_rename_lenme_fee_loan_admin_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, help_text='The amount requested by the borrower.', max_digits=10)),
                ('total_repayable_amount', models.DecimalField(decimal_places=2, help_text='Total amount to be repaid including fees.', max_digits=10)),
                ('processing_fee', models.DecimalField(decimal_places=2, help_text='Administrative or processing fee for the loan.', max_digits=10)),
                ('repayment_period_months', models.PositiveIntegerField(help_text='Number of months over which the loan will be repaid.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
