# Generated by Django 4.2.16 on 2024-09-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_loanrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrequest',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='processing_fee',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='total_repayable_amount',
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
