# Generated by Django 4.2.16 on 2024-09-09 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0008_rename_created_at_loanrequest_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_amount', models.DecimalField(decimal_places=2, help_text='The amount offered by the lender.', max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate offered by the lender (as a percentage).', max_digits=5)),
                ('total_repayable_amount', models.DecimalField(decimal_places=2, help_text='Total amount to be repaid including interest.', max_digits=10)),
                ('offer_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', help_text='Status of the loan offer.', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_offers', to=settings.AUTH_USER_MODEL)),
                ('loan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='loans.loanrequest')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='loans.loanoffer'),
        ),
    ]
