# Generated by Django 4.2.16 on 2024-09-09 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0007_loanrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount transferred.', max_digits=10)),
                ('transfer_type', models.CharField(choices=[('add_money', 'Add Money'), ('withdrawal', 'Withdrawal'), ('fund_loan', 'Fund Loan'), ('monthly_payment', 'Monthly Payment'), ('collection', 'Collection')], default='fund_loan', help_text='The type of transfer.', max_length=20)),
                ('transfer_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='The status of the transfer.', max_length=20)),
                ('from_account', models.CharField(blank=True, help_text='Source of the transfer, can be a user wallet or external account.', max_length=255, null=True)),
                ('to_account', models.CharField(blank=True, help_text='Destination of the transfer, can be a user wallet or external account.', max_length=255, null=True)),
                ('transfer_source_dest', models.CharField(help_text='Details about the source or destination of the transfer.', max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the transfer was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Timestamp when the transfer was last modified.')),
                ('borrower', models.ForeignKey(blank=True, help_text='The borrower associated with the transfer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrower_transfers', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(blank=True, help_text='The loan associated with the transfer.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.loan')),
                ('loan_request', models.ForeignKey(blank=True, help_text='The loan request associated with the transfer.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.loanrequest')),
                ('user', models.ForeignKey(help_text='The user associated with the transfer.', on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
