# Generated by Django 4.2.16 on 2024-09-09 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='transfer_source_dest',
        ),
    ]
