# Generated by Django 4.2.16 on 2024-09-09 07:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0007_loanrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, help_text='The amount paid for this installment.', max_digits=10)),
                ('payment_due_date', models.DateField(help_text='The due date for the payment.')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', help_text='Status of the payment.', max_length=20)),
                ('payment_status_changed', models.DateTimeField(blank=True, help_text='Timestamp when the payment status was last changed.', null=True)),
                ('late_payment_fees_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount of fees charged for late payment.', max_digits=10, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the payment record was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Timestamp when the payment record was last modified.')),
                ('is_late_payment', models.BooleanField(default=False, help_text='Indicates whether the payment was made late.')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan')),
            ],
        ),
    ]
